services:
  web:
    build: .
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgresql://theobessel:root@db:5432/grinp
      ORIGIN: http://4.233.209.231
      REDIRECT_URI: http://4.233.209.231/login
      DEV: true
    ports:
      - "80:3000"
    depends_on: [db]
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: theobessel
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grinp
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
